# Generated by Django 5.0 on 2024-01-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_excercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='time_taken',
        ),
    ]
